### ISSUE TITLE
Clarity, readability and content improvements for the lite node getting started page

### ISSUE THREAD

**Issue by guillheu** [PowerLoom/docs#12]
**Is your feature request related to a problem?**
The `getting-started` page for lite node setup could be improved.

**Describe the solution you'd like**
- listing hardware requirements once
- reorganizing sections to be more readable
- adding tabs for linux/windows platforms

**Comment by thecoderpanda** [comment]
Hi @guillheu, Thanks for your contribution. Will review this!
