### ISSUE TITLE
Documentation not fully made

### ISSUE THREAD

**Issue by Speedevs** [PowerLoom/docs#14]
The following we node runners need .

- [x] Hardware Requirements:
- [ ] Networking Requirements: (Firewall and Ports etc)
- [x] Software Requirements: (Windows, Linux , Unbuntu(be specific which versions)
- [x] Monitoring and Management: (Where to see logs if it failed etc)
- [ ] Language translations if possible for people in other countries .

But I think this is the basic needed for us to run node.

<img width="780" alt="image" src="https://github.com/PowerLoom/docs/assets/45816964/d49f2598-4576-48fa-b4b4-6bfec1896bac">
The "SSH" , you should also mention the "SSH" we should use .

**Comment by Speedevs** [comment]
Also the "examples" , something should be fixed about that

**Comment by Speedevs** [comment]
https://powerloom.network/mint-docs/

Also your team should have add this to the documentation too .

**Comment by kanikamishra** [comment]
For language use google translate on the browser

**Comment by Speedevs** [comment]
Most places requires different requirements.
Like some specific ports to be opened etc 
If that can be clarified
