### ISSUE TITLE
Document has a wrong link

### ISSUE THREAD

**Issue by SeungjinPark2** [PowerLoom/docs#35]
## Describe the bug 
On page https://docs.powerloom.io/docs/Protocol/Specifications/protocol-state
![image](https://github.com/PowerLoom/docs/assets/17927890/3138723b-b23f-41f3-8ee3-99d15a7a1a9e)
A link for data market redirects to 404 page.

Wrong url linking causes 404 error especially on paths below.
- https://docs.powerloom.io/docs/protocol/
- https://docs.powerloom.io/docs/protocol/specifications
- https://docs.powerloom.io/docs/protocol/specifications/snapshotter
- https://docs.powerloom.io/docs/protocol/specifications/epoch

The tokens (protocol, specifications, snapshotter, epoch) should start with capital letter.

## To Reproduce

1. Go to the page On page https://docs.powerloom.io/docs/Protocol/Specifications/protocol-state
2. Click an anchor element - "data market"
3. Check it redirects to 404 page.

**Expected behavior**
Anchor tags linked to paths I described should redirect to a proper page not a 404 page.

**Proposed Solution**
Find wrong url links that do not start with capital letter and fix them.

**Caveats**
It does not seem to have any suspected impact on the solution.

**Additional context**
No additional context

**Comment by SeungjinPark2** [comment]
I found many links redirecting to 404.
I created [PR](https://github.com/PowerLoom/docs/pull/36#issue-2275357284)

**Comment by SwaroopH** [comment]
hey @SeungjinPark2, thanks for catching this. Could you please follow the guidelines in the issue and PR template?

**Comment by SeungjinPark2** [comment]
Hi @SwaroopH, I've done to edit issue, pr.

**Comment by anomit** [comment]
Closing this since it has been clarified in detail in issue #36
