### ISSUE TITLE
UniswapV3 use case docs

### ISSUE THREAD

**Issue by Seth-Schmidt** [PowerLoom/docs#38]
**Is your feature request related to a problem?**
The UniswapV3 use case needs to be referenced in the Existing Use Cases section of the docs 

**Describe the solution you'd like**
Considering the many similarities between the Uniswap V2 and V3 use cases, the V3 docs should be included in a general Uniswap use case section with links to both the V2 and V3 compute/config repos as well as the already present breakdown of data points.

**Describe alternatives you've considered**
V3 could have a standalone section under Existing Use Cases, but there would be a large amount of duplicate data between the V2 and V3 sections.

**Comment by anomit** [comment]
Review comments left on PR #39 @Seth-Schmidt

**Comment by Seth-Schmidt** [comment]
The feature has been merged here: https://github.com/PowerLoom/docs/pull/39

Closing
